spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.yml

cluster:
  nodes:
    - address: http://cert-node1:8080
    - address: http://cert-node2:8080
    - address: http://cert-node3:8080
