spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gift-certificate-db
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
