spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.yml

cluster:
  shards:
    - - cert-node11:8080
      - cert-node12:8080
      - cert-node13:8080

    - - cert-node21:8080
      - cert-node22:8080
      - cert-node23:8080

    - - cert-node31:8080
      - cert-node32:8080
      - cert-node33:8080
  url-prefix: http://
