spring:
  datasource:
    url: jdbc:postgresql://11.11.11.11:5432/gift-certificate-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect